// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'weekly_model.freezed.dart';

@freezed
class WeeklyModel with _$WeeklyModel {
  const factory WeeklyModel() = _WeeklyModel;
}
