// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import '../02_split/split_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'plans_model.freezed.dart';

@freezed
class TrainingPlan with _$TrainingPlan {
  const factory TrainingPlan({
    required String name,
    required List<TrainingSplit> splits,
  }) = _TrainingPlan;
}
