// This file is "main.dart"
import 'package:buddybuilder/services/db/collections/split.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'edit_plan_model.freezed.dart';

@freezed
class EditPlanModel with _$EditPlanModel {
  const factory EditPlanModel({
    required int id,
    required String name,
    required List<Split> splits,
  }) = _EditPlanModel;
}
