// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'edit_split_model.freezed.dart';

@freezed
class EditSplitModel with _$EditSplitModel {
  const factory EditSplitModel({
    required List workoutList,
    required String workoutTitle,
    required List widgetList,
    required int setId,
    String? searchQuery,
  }) = _EditSplitModel;
}
