// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'rotation_model.freezed.dart';

@freezed
class RotationModel with _$RotationModel {
  const factory RotationModel() = _RotationModel;
}
