// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import '../03_workout/workout_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'split_model.freezed.dart';

@freezed
class TrainingSplit with _$TrainingSplit {
  const factory TrainingSplit({
    required String name,
    required List<Workout> workouts,
  }) = _TrainingSplit;
}
