// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'create_plan_model.freezed.dart';

@freezed
class PlanModel with _$PlanModel {
  const factory PlanModel() = _PlanModel;
}
