// This file is "main.dart"
import 'package:buddybuilder/services/db/collections/plan.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'plan_model.freezed.dart';

@freezed
class PlanModel with _$PlanModel {
  const factory PlanModel({
    required int id,
    required String name,
    required List<Split> splits,
  }) = _PlanModel;
}
