// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'set_model.freezed.dart';

@freezed
class ExerciseSet with _$ExerciseSet {
  const factory ExerciseSet({
    required String name,
    required int reps,
    required double weight,
  }) = _ExerciseSet;
 

}
