// This file is "main.dart"
import 'package:buddybuilder/pages/create_plan/04_set/set_model.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'workout_model.freezed.dart';

@freezed
class Workout with _$Workout {
  const factory Workout({
    required String name,
    required List<ExerciseSet> sets,
  }
  ) = _Workout;
}
